(define pi  3.1415926)

(define (circle r t) (cons (* r (cos t)) (* r (sin t))))
(define (translate v curve)
  (lambda (t) (let ((p (curve t))) 
    (cons 
      (+ (car v) (car p))
      (+ (cdr v) (cdr p))))))
(define (test) 
  ((new-graph "blue" 2 "test.svg")
   (translate (cons 9 9) 
     (lambda (t) 
     (circle 10 t)))
   0 (* 2 pi)))
(test)
